apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "mtc.name" . }}-{{ .Release.Name }}-app
  labels:
    app: {{ template "mtc.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.mtc.replicaCount }} 
  selector:
    matchLabels:
      app: {{ template "mtc.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      tier: app
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "mtc.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        tier: app
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.mtc.nginx.image.repo }}:{{ .Values.mtc.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.mtc.nginx.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health.json
            port: {{ .Values.mtc.nginx.port }} 
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: {{ .Values.mtc.nginx.port }} 
          name: nginx
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html
          name: nfs
          readOnly: true
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginx
          subPath: default.conf

      - name: php
        image: "{{ .Values.mtc.php.image.repo }}:{{ .Values.mtc.php.image.tag }}"
        imagePullPolicy: {{ .Values.mtc.php.image.pullPolicy }}
        env:
        - name: XENAPI_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: {{ template "mtc.name" . }}-{{ .Release.Name }}-xenapi-token
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ template "mtc.name" . }}-{{ .Release.Name }}-mysql-password
        lifecycle:
          postStart:
            exec:
              command:
              - /usr/local/bin/setup.sh
        ports:
        - containerPort: {{ .Values.mtc.php.port }} 
          name: php-fpm
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 250Mi
          requests:
            cpu: 200m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/mtc
          name: nfs
        - mountPath: /var/www/html/library/config.php
          name: config
          subPath: config.php

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: {{ .Values.mtc.volumeClaim }} 
      - name: nginx
        configMap:
          name: {{ template "mtc.name" . }}-{{ .Release.Name }}-nginx
          defaultMode: 420
      - name: config
        configMap:
          name: {{ template "mtc.name" . }}-{{ .Release.Name }}-config
          defaultMode: 420

