apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mtc.name" . }}-{{ .Release.Name }}-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
